### PR TITLE
Fix undefined tabs

### LINKED ISSUE #251: Search list empty
Often when opening Quick Tabs and typing a search term, the search list will be empty.
This may be related to hibernating windows, or perhaps just after a length of time has passed.

I'm not sure if relevant, but the tab count indicator is often also orange when this issue occurs, and sometimes reads an incorrect tab amount (possibly double).

I have to disable and re-enable the extension for search to resume working correctly.

Using Windows 7 64bit, Chrome 71.0.3578.98 64-bit

### LINKED ISSUE #275: Tab count stops counting down
At some point while using chrome, the tab count in the extension badge stops counting down when closing tabs but does increment when opening tabs. 

Toggling the extension on and off resolves the issue temporarily. I haven't noticed a pattern for when the count stops decrementing

### LINKED ISSUE #310: No tabs showing up!
quick-tabs-malfunction

### LINKED ISSUE #313: Quick Tabs fails to update and breaks after tabs are closed via OneTab
When using the OneTab extension to collapse/close tabs, quick tabs fails to realize the tabs are closed and update accordingly.  Closing multiple tabs with one tab also seems to "corrupt" quick tabs, causing no tabs to be displayed and the tab switching feature to no longer function.

I have not been able to figure out a way to get quick tabs to refresh/update so it is aware of currently open tabs (and aware that many of the previous tabs were closed).

### PR DESCRIPTION
**Pull request by NicoWeio**
I am aware that my proposed solution is not ideal. But it has little impact on code size and performance, so unless we know _why_ tabs are undefined, fixing these crashes _somehow_ is probably a good idea. 

Fixes #251, closes #310, closes #275, closes #313.

### CODE REVIEW

File: quick-tabs/background.js [hunk 1]
```diff
@@ -481,7 +485,7 @@ function initBadgeIcon() {
  */
 function updateBadgeText() {
   if (showTabCount()) {
-    var val = tabs.filter(includeTab).length;
+    var val = tabs.filter(validTab).filter(includeTab).length;
```
Comment (tobiasl-sportsbet) [inline quick-tabs/background.js:488]: Might I suggest that you run both functions together rather than using a second array method, as every chained array method means the creation of a new array.

```suggestion
    var val = tabs.filter(tab => validTab(tab) && includeTab(tab)).length;
```

It is a small performance optimization for sure but limiting the use of unnecessary array methods can add up over time with lowering memory usage.

File: quick-tabs/popup.js [hunk 2]
```diff
@@ -770,20 +770,24 @@ AbstractSearch.prototype.executeSearch = function(query, searchBookmark, searchH
...
+  }
+
   if (query.trim().length === 0) {
     // no need to search if the string is empty
-    filteredTabs = bg.tabs;
+    filteredTabs = checkTabs(bg.tabs);
     filteredClosed = bg.closedTabs;
   } else if (query === "<))") {
-    filteredTabs = bg.tabs.filter(filterAudible)
+    filteredTabs = checkTabs(bg.tabs.filter(filterAudible))
```
Comment (tobiasl-sportsbet) [inline quick-tabs/popup.js:782]: Same could be done here, rather than filtering the result of a filter, do the check for a `tab.title` within a single filter where `filterAudible` is passed into.

File: quick-tabs/background.js (hunk 1 above)
Comment (NicoWeio) [reply quick-tabs/background.js]: Sure thing! Fixed that.

File: quick-tabs/popup.js (hunk 2 above)
Comment (NicoWeio) [reply quick-tabs/popup.js]: Fixed as well.

**Comment by babyman** [comment]
Thank you @NicoWeio, I'll get this pushed today once I give it a quick test drive.
